//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FillingStation.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FillingStation.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string AddRecord {
            get {
                return ResourceManager.GetString("AddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - collector: {0} sec.
        /// </summary>
        public static string AVG_CarCasherFormat {
            get {
                return ResourceManager.GetString("AVG_CarCasherFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AVG count of cars: {0}.
        /// </summary>
        public static string AVG_CarCount {
            get {
                return ResourceManager.GetString("AVG_CarCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AVG filling check: {0} $.
        /// </summary>
        public static string AVG_CarFillingCashFormat {
            get {
                return ResourceManager.GetString("AVG_CarFillingCashFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AVG filling tank: {0} liters.
        /// </summary>
        public static string AVG_CarFillingTankFormat {
            get {
                return ResourceManager.GetString("AVG_CarFillingTankFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AVG filling time: {0} sec.
        /// </summary>
        public static string AVG_CarFillingTimeFormat {
            get {
                return ResourceManager.GetString("AVG_CarFillingTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AVG inter-arrival time of:.
        /// </summary>
        public static string AVG_CarServiceCarWaiting {
            get {
                return ResourceManager.GetString("AVG_CarServiceCarWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - tanker (A92): {0} sec.
        /// </summary>
        public static string AVG_CarTank92Format {
            get {
                return ResourceManager.GetString("AVG_CarTank92Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - tanker (A95): {0} sec.
        /// </summary>
        public static string AVG_CarTank95Format {
            get {
                return ResourceManager.GetString("AVG_CarTank95Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - tanker (A98: {0} sec.
        /// </summary>
        public static string AVG_CarTank98Format {
            get {
                return ResourceManager.GetString("AVG_CarTank98Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - tanker (Diesel): {0} sec.
        /// </summary>
        public static string AVG_CarTankDieselFormat {
            get {
                return ResourceManager.GetString("AVG_CarTankDieselFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AVG service time: {0} sec.
        /// </summary>
        public static string AVG_CarTimeFormat {
            get {
                return ResourceManager.GetString("AVG_CarTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Percentage of cars which entered FS: {0} %.
        /// </summary>
        public static string AVG_CarToFSFormat {
            get {
                return ResourceManager.GetString("AVG_CarToFSFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User car.
        /// </summary>
        public static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int16, аналогичного 1.
        /// </summary>
        public static short Car_carSize {
            get {
                object obj = ResourceManager.GetObject("Car_carSize", resourceCulture);
                return ((short)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int16, аналогичного 2.
        /// </summary>
        public static short Car_fuel {
            get {
                object obj = ResourceManager.GetObject("Car_fuel", resourceCulture);
                return ((short)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vehicles/Cars/vh_car_5.png.
        /// </summary>
        public static string Car_path {
            get {
                return ResourceManager.GetString("Car_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Decimal, аналогичного 50.
        /// </summary>
        public static decimal Car_tankVolume {
            get {
                object obj = ResourceManager.GetObject("Car_tankVolume", resourceCulture);
                return ((decimal)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car percentage, %.
        /// </summary>
        public static string CarPercentage {
            get {
                return ResourceManager.GetString("CarPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cars.
        /// </summary>
        public static string Cars {
            get {
                return ResourceManager.GetString("Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car:.
        /// </summary>
        public static string CarSizeType {
            get {
                return ResourceManager.GetString("CarSizeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cars.
        /// </summary>
        public static string CarsTitle {
            get {
                return ResourceManager.GetString("CarsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car stream.
        /// </summary>
        public static string CarStreamSettingsTitle {
            get {
                return ResourceManager.GetString("CarStreamSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cash box: {0} $.
        /// </summary>
        public static string Cash_state {
            get {
                return ResourceManager.GetString("Cash_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cash box.
        /// </summary>
        public static string CashBox {
            get {
                return ResourceManager.GetString("CashBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cash box&apos;s limit.
        /// </summary>
        public static string CashBox_limit {
            get {
                return ResourceManager.GetString("CashBox_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pt_cash_box.png.
        /// </summary>
        public static string CashBox_path {
            get {
                return ResourceManager.GetString("CashBox_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collector.
        /// </summary>
        public static string Casher {
            get {
                return ResourceManager.GetString("Casher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vehicles/vh_casher.png.
        /// </summary>
        public static string Casher_path {
            get {
                return ResourceManager.GetString("Casher_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Column.
        /// </summary>
        public static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pt_kol.png.
        /// </summary>
        public static string Column_path {
            get {
                return ResourceManager.GetString("Column_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose cell. &lt;ESC&gt; to cancel.
        /// </summary>
        public static string Construction_placeOnCell {
            get {
                return ResourceManager.GetString("Construction_placeOnCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace to another cell..
        /// </summary>
        public static string Construction_placeOnNewCell {
            get {
                return ResourceManager.GetString("Construction_placeOnNewCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string DeleteRecord {
            get {
                return ResourceManager.GetString("DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deterministic.
        /// </summary>
        public static string Determin {
            get {
                return ResourceManager.GetString("Determin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ΔT (sec):.
        /// </summary>
        public static string Determin_dt {
            get {
                return ResourceManager.GetString("Determin_dt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cash box must be near road..
        /// </summary>
        public static string Exception_cashNearRoad {
            get {
                return ResourceManager.GetString("Exception_cashNearRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error proced in database!.
        /// </summary>
        public static string Exception_DB {
            get {
                return ResourceManager.GetString("Exception_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There must be more than 1 record.
        /// </summary>
        public static string Exception_DB_singleDelete {
            get {
                return ResourceManager.GetString("Exception_DB_singleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Y must be from 0.001 to 0.5.
        /// </summary>
        public static string Exception_ExponentialRange {
            get {
                return ResourceManager.GetString("Exception_ExponentialRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filling tank volume must be from {0} to {1}..
        /// </summary>
        public static string Exception_FillingVolumeFormat {
            get {
                return ResourceManager.GetString("Exception_FillingVolumeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filling station is incorrect. May be not all roads are connected..
        /// </summary>
        public static string Exception_FSIsIncorrect {
            get {
                return ResourceManager.GetString("Exception_FSIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cash box&apos;s limit must be from 500 000 to 1 500 000..
        /// </summary>
        public static string Exception_FSModelCorrectness_CashRangeFormat {
            get {
                return ResourceManager.GetString("Exception_FSModelCorrectness_CashRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}&apos;s tank limit must be from {1} to critical.
        /// </summary>
        public static string Exception_FSModelCorrectness_CriticalTankLimitFormat {
            get {
                return ResourceManager.GetString("Exception_FSModelCorrectness_CriticalTankLimitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}&apos;s low tank limit must be from {1} to limit..
        /// </summary>
        public static string Exception_FSModelCorrectness_LowTankLimitFormat {
            get {
                return ResourceManager.GetString("Exception_FSModelCorrectness_LowTankLimitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на «{0}» does not connected to main road..
        /// </summary>
        public static string Exception_FSModelCorrectness_PatternMainRoadFormat {
            get {
                return ResourceManager.GetString("Exception_FSModelCorrectness_PatternMainRoadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Some roads are not available for vehicles. Probably, there are some loops on FS..
        /// </summary>
        public static string Exception_FSModelCorrectness_PatternsNotUsed {
            get {
                return ResourceManager.GetString("Exception_FSModelCorrectness_PatternsNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter pattern must be before Exit pattern..
        /// </summary>
        public static string Exception_FSModelCorrectness_RoadInOut {
            get {
                return ResourceManager.GetString("Exception_FSModelCorrectness_RoadInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}&apos;s tank limit must be from {1} to {2}..
        /// </summary>
        public static string Exception_FSModelCorrectness_TankLimitRangeFormat {
            get {
                return ResourceManager.GetString("Exception_FSModelCorrectness_TankLimitRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tank&apos;s limit must be from 10 000 to 20 000..
        /// </summary>
        public static string Exception_FSModelCorrectness_TankRange {
            get {
                return ResourceManager.GetString("Exception_FSModelCorrectness_TankRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There must be exactly {0} «{1}»..
        /// </summary>
        public static string Exception_FSModelCorrectnessFormat {
            get {
                return ResourceManager.GetString("Exception_FSModelCorrectnessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field&apos;s width must be from {0} to {1}.
        ///Field&apos;s height must be from {2} to {3}..
        /// </summary>
        public static string Exception_FSModelRangeFormat {
            get {
                return ResourceManager.GetString("Exception_FSModelRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argumet is not fuel type.
        /// </summary>
        public static string Exception_fuel {
            get {
                return ResourceManager.GetString("Exception_fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price must be from {0} to {1}..
        /// </summary>
        public static string Exception_FuelPriceFormat {
            get {
                return ResourceManager.GetString("Exception_FuelPriceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There is an error on creating car stream:.
        /// </summary>
        public static string Exception_Generator {
            get {
                return ResourceManager.GetString("Exception_Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You should choose some stream before continue.
        /// </summary>
        public static string Exception_GeneratorNotChoosen {
            get {
                return ResourceManager.GetString("Exception_GeneratorNotChoosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are no {0} files..
        /// </summary>
        public static string Exception_HtmlNotFoundFormat {
            get {
                return ResourceManager.GetString("Exception_HtmlNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could&apos;t create class of type..
        /// </summary>
        public static string Exception_missingClass {
            get {
                return ResourceManager.GetString("Exception_missingClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на mx must be from 2 to 100.
        /// </summary>
        public static string Exception_NormalRange {
            get {
                return ResourceManager.GetString("Exception_NormalRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This are no rotation property.
        /// </summary>
        public static string Exception_notRotaion {
            get {
                return ResourceManager.GetString("Exception_notRotaion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could&apos;t place pattern at this point..
        /// </summary>
        public static string Exception_pattern_place {
            get {
                return ResourceManager.GetString("Exception_pattern_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Percent couldn&apos;t be less than 0..
        /// </summary>
        public static string Exception_PercentageMustBeNonNegativeValue {
            get {
                return ResourceManager.GetString("Exception_PercentageMustBeNonNegativeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Path doesn&apos;t contain this point.
        /// </summary>
        public static string Exception_point_is_not_on_path {
            get {
                return ResourceManager.GetString("Exception_point_is_not_on_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на must be positive integer.
        /// </summary>
        public static string Exception_positive_int {
            get {
                return ResourceManager.GetString("Exception_positive_int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mistake at: &quot;{0}&quot;..
        /// </summary>
        public static string Exception_properyFormat {
            get {
                return ResourceManager.GetString("Exception_properyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred while loading filling station.\n.
        /// </summary>
        public static string Exception_readFS {
            get {
                return ResourceManager.GetString("Exception_readFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Segment count must be from 1 to 4.
        /// </summary>
        public static string Exception_segment_count {
            get {
                return ResourceManager.GetString("Exception_segment_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Simulation speed wasn&apos;t write correctly..
        /// </summary>
        public static string Exception_SimulationSpeed {
            get {
                return ResourceManager.GetString("Exception_SimulationSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Simulation speed must be more than {0} and no more than {1}..
        /// </summary>
        public static string Exception_SimulationSpeedRange {
            get {
                return ResourceManager.GetString("Exception_SimulationSpeedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sum of all percentages must equals 100%.
        /// </summary>
        public static string Exception_SumPercentage {
            get {
                return ResourceManager.GetString("Exception_SumPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uniform range must be from 2 to 100.
        /// </summary>
        public static string Exception_UniformRange {
            get {
                return ResourceManager.GetString("Exception_UniformRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field&apos;s width must be from {0} to {1}.
        ///Field&apos;s height must be from {2} to {3}..
        /// </summary>
        public static string Exception_WidthRangeFormat {
            get {
                return ResourceManager.GetString("Exception_WidthRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred while saving filling station.\n.
        /// </summary>
        public static string Exception_writeFS {
            get {
                return ResourceManager.GetString("Exception_writeFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string ExceptionMessage_Title {
            get {
                return ResourceManager.GetString("ExceptionMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Determin range must be from 2 to 100.
        /// </summary>
        public static string Exeption_DeterminRange {
            get {
                return ResourceManager.GetString("Exeption_DeterminRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There couldn&apos;t be such dx and mx..
        /// </summary>
        public static string Exeption_Normal {
            get {
                return ResourceManager.GetString("Exeption_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exponential.
        /// </summary>
        public static string Exponential {
            get {
                return ResourceManager.GetString("Exponential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field&apos;s settings.
        /// </summary>
        public static string FieldSettings {
            get {
                return ResourceManager.GetString("FieldSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filling station.
        /// </summary>
        public static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Noname.
        /// </summary>
        public static string Filename_noname {
            get {
                return ResourceManager.GetString("Filename_noname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filling volume, liters.
        /// </summary>
        public static string FillingVolume {
            get {
                return ResourceManager.GetString("FillingVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All.
        /// </summary>
        public static string Filter_all {
            get {
                return ResourceManager.GetString("Filter_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FS model.
        /// </summary>
        public static string Filter_model {
            get {
                return ResourceManager.GetString("Filter_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filling station.
        /// </summary>
        public static string FSSettingsTitle {
            get {
                return ResourceManager.GetString("FSSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на State.
        /// </summary>
        public static string FSState {
            get {
                return ResourceManager.GetString("FSState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Statistics.
        /// </summary>
        public static string FSStatistics {
            get {
                return ResourceManager.GetString("FSStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuel.
        /// </summary>
        public static string Fuel {
            get {
                return ResourceManager.GetString("Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A - 92.
        /// </summary>
        public static string Fuel_a92 {
            get {
                return ResourceManager.GetString("Fuel_a92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A - 95.
        /// </summary>
        public static string Fuel_a95 {
            get {
                return ResourceManager.GetString("Fuel_a95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A - 98.
        /// </summary>
        public static string Fuel_a98 {
            get {
                return ResourceManager.GetString("Fuel_a98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Diesel.
        /// </summary>
        public static string Fuel_diesel {
            get {
                return ResourceManager.GetString("Fuel_diesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuel consumption settings.
        /// </summary>
        public static string FuelConsumptionSettingsTitle {
            get {
                return ResourceManager.GetString("FuelConsumptionSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuel.
        /// </summary>
        public static string FuelTitle {
            get {
                return ResourceManager.GetString("FuelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuel type:.
        /// </summary>
        public static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image:.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information board.
        /// </summary>
        public static string InfoTable {
            get {
                return ResourceManager.GetString("InfoTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pt_table.png.
        /// </summary>
        public static string InfoTable_path {
            get {
                return ResourceManager.GetString("InfoTable_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manually.
        /// </summary>
        public static string Manually {
            get {
                return ResourceManager.GetString("Manually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Model: .
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Simulation time: .
        /// </summary>
        public static string ModelTime {
            get {
                return ResourceManager.GetString("ModelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        public static string NextRecord {
            get {
                return ResourceManager.GetString("NextRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dx (sec^2):.
        /// </summary>
        public static string Normal_dx {
            get {
                return ResourceManager.GetString("Normal_dx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на mx (sec):.
        /// </summary>
        public static string Normal_mx {
            get {
                return ResourceManager.GetString("Normal_mx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на y (1/sec):.
        /// </summary>
        public static string Normal_y {
            get {
                return ResourceManager.GetString("Normal_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        public static string PreviousRecord {
            get {
                return ResourceManager.GetString("PreviousRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Liter price.
        /// </summary>
        public static string PricePerLiter {
            get {
                return ResourceManager.GetString("PricePerLiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price per liter, $.
        /// </summary>
        public static string PricePerLitter {
            get {
                return ResourceManager.GetString("PricePerLitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filling Station simulation program.
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name: .
        /// </summary>
        public static string PropertyName {
            get {
                return ResourceManager.GetString("PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Road.
        /// </summary>
        public static string Road {
            get {
                return ResourceManager.GetString("Road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pt_road.png.
        /// </summary>
        public static string Road_path {
            get {
                return ResourceManager.GetString("Road_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter.
        /// </summary>
        public static string RoadIn {
            get {
                return ResourceManager.GetString("RoadIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pt_road_in.png.
        /// </summary>
        public static string RoadIn_path {
            get {
                return ResourceManager.GetString("RoadIn_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string RoadOut {
            get {
                return ResourceManager.GetString("RoadOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pt_road_out.png.
        /// </summary>
        public static string RoadOut_path {
            get {
                return ResourceManager.GetString("RoadOut_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сrossroad.
        /// </summary>
        public static string RoadT {
            get {
                return ResourceManager.GetString("RoadT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pt_road_t.png.
        /// </summary>
        public static string RoadT_path {
            get {
                return ResourceManager.GetString("RoadT_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turn.
        /// </summary>
        public static string RoadTurn {
            get {
                return ResourceManager.GetString("RoadTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pt_road_turn.png.
        /// </summary>
        public static string RoadTurn_path {
            get {
                return ResourceManager.GetString("RoadTurn_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project isn&apos;t saved. Save it?.
        /// </summary>
        public static string SaveProject {
            get {
                return ResourceManager.GetString("SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string SaveRecord {
            get {
                return ResourceManager.GetString("SaveRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Properties.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Simulation.
        /// </summary>
        public static string Simulation {
            get {
                return ResourceManager.GetString("Simulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Simulation.
        /// </summary>
        public static string SimulationTitle {
            get {
                return ResourceManager.GetString("SimulationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tank.
        /// </summary>
        public static string Tank {
            get {
                return ResourceManager.GetString("Tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tank (A92): {0} liters.
        /// </summary>
        public static string Tank_a92_state {
            get {
                return ResourceManager.GetString("Tank_a92_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tank (A95): {0} liters.
        /// </summary>
        public static string Tank_a95_state {
            get {
                return ResourceManager.GetString("Tank_a95_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tank (A98): {0} liters.
        /// </summary>
        public static string Tank_a98_state {
            get {
                return ResourceManager.GetString("Tank_a98_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tank (Diesel): {0} liters.
        /// </summary>
        public static string Tank_diesel_state {
            get {
                return ResourceManager.GetString("Tank_diesel_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Critical fuel level:.
        /// </summary>
        public static string Tank_fuel_critical {
            get {
                return ResourceManager.GetString("Tank_fuel_critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuel type: .
        /// </summary>
        public static string Tank_fuel_field {
            get {
                return ResourceManager.GetString("Tank_fuel_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Low fuel level:.
        /// </summary>
        public static string Tank_fuel_low {
            get {
                return ResourceManager.GetString("Tank_fuel_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tank&apos;s limit: .
        /// </summary>
        public static string Tank_limit {
            get {
                return ResourceManager.GetString("Tank_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pt_rez.png.
        /// </summary>
        public static string Tank_path {
            get {
                return ResourceManager.GetString("Tank_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tanker.
        /// </summary>
        public static string Tanker {
            get {
                return ResourceManager.GetString("Tanker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tank&apos;s volume.
        /// </summary>
        public static string TankVolume {
            get {
                return ResourceManager.GetString("TankVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turn: .
        /// </summary>
        public static string Turn {
            get {
                return ResourceManager.GetString("Turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uniform.
        /// </summary>
        public static string Uniform {
            get {
                return ResourceManager.GetString("Uniform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a (sec):.
        /// </summary>
        public static string Uniform_a {
            get {
                return ResourceManager.GetString("Uniform_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b (sec):.
        /// </summary>
        public static string Uniform_b {
            get {
                return ResourceManager.GetString("Uniform_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
